sonar.projectKey=sarusman_rent
sonar.organization=sarusman

sonar.sources=MyService/app,MyService/src/main/java
sonar.tests=MyService/tests,MyService/src/test/java

sonar.python.version=3.12
sonar.python.coverage.reportPaths=MyService/coverage.xml

sonar.java.source=21
sonar.coverage.jacoco.xmlReportPaths=MyService/build/reports/jacoco/test/jacocoTestReport.xml
